(function(root){
 'use strict';
 const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const names={'bull-call':'Bull call debit spread','bear-put':'Bear put debit spread','bull-put':'Bull put credit spread','bear-call':'Bear call credit spread',straddle:'Long straddle',strangle:'Long strangle',condor:'Iron condor',butterfly:'Call butterfly',covered:'Covered call',protective:'Protective put',secured:'Cash-secured put',collar:'Collar'};
 function create(market,callbacks){
  let legs=[],stockRatio=0,custom=false,protectedPosition=null;
  const option=Northstar.option;
  $('builder-symbol').innerHTML=Northstar.SEEDS.map(([s,n])=>`<option value="${s}">${s} — ${n}</option>`).join('');
  function underlying(){return market.state.stocks[$('builder-symbol').value];}
  function expiration(){const old=Number($('builder-expiry').value),base=new Date(market.state.clock);base.setUTCHours(20,0,0,0);base.setUTCDate(base.getUTCDate()+((5-base.getUTCDay()+7)%7||7));const options=[0,7,14,28,56,84,168].map(d=>base.getTime()+d*86400000);if(old>market.state.clock&&!options.includes(old))options.unshift(old);$('builder-expiry').innerHTML=options.map(t=>`<option value="${t}">${new Date(t).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})} · ${Math.ceil((t-market.state.clock)/86400000)}d</option>`).join('');if(options.includes(old))$('builder-expiry').value=old;}
  function draft(){return {kind:'package',symbol:underlying().symbol,name:custom?'Custom option strategy':names[$('builder-template').value],expiry:Number($('builder-expiry').value),qty:Number($('builder-qty').value),stockRatio,legs:legs.map(l=>({...l}))};}
  function seed(){const s=underlying(),step=s.price<50?1:s.price<200?2.5:s.price<500?5:10,k=Math.round(s.price/step)*step;const leg=(type,strike,ratio)=>({type,strike:Math.max(step,strike),ratio});const templates={
   'bull-call':[leg('call',k,1),leg('call',k+step*2,-1)],
   'bear-put':[leg('put',k,1),leg('put',k-step*2,-1)],
   'bull-put':[leg('put',k-step,-1),leg('put',k-step*3,1)],
   'bear-call':[leg('call',k+step,-1),leg('call',k+step*3,1)],
   straddle:[leg('call',k,1),leg('put',k,1)],
   strangle:[leg('put',k-step*2,1),leg('call',k+step*2,1)],
   condor:[leg('put',k-step*3,1),leg('put',k-step,-1),leg('call',k+step,-1),leg('call',k+step*3,1)],
   butterfly:[leg('call',k-step*2,1),leg('call',k,-2),leg('call',k+step*2,1)],covered:[leg('call',k+step*2,-1)],protective:[leg('put',k-step*2,1)],secured:[leg('put',k-step*2,-1)],collar:[leg('put',k-step*2,1),leg('call',k+step*2,-1)]};legs=templates[$('builder-template').value];stockRatio=['covered','protective','collar'].includes($('builder-template').value)?1:0;custom=false;$('whatif-price').value=s.price.toFixed(2);$('whatif-iv').value=(s.vol*100).toFixed(0);$('whatif-days').value=0;renderLegs();render();}
  function renderLegs(){const p=draft();$('builder-stock').hidden=!stockRatio;$('builder-stock').textContent='Stock leg: buy 100 '+p.symbol+' shares per strategy unit. These shares are held inside the strategy package.';$('builder-legs').innerHTML=legs.map((l,i)=>`<tr><td><select data-leg="${i}" data-field="side" aria-label="Leg ${i+1} action"><option value="1" ${l.ratio>0?'selected':''}>Buy to open</option><option value="-1" ${l.ratio<0?'selected':''}>Sell to open</option></select></td><td><select data-leg="${i}" data-field="type" aria-label="Leg ${i+1} type"><option value="call" ${l.type==='call'?'selected':''}>Call</option><option value="put" ${l.type==='put'?'selected':''}>Put</option></select></td><td><input data-leg="${i}" data-field="strike" aria-label="Leg ${i+1} strike" type="number" min="0.5" step="0.5" value="${l.strike}"></td><td><input data-leg="${i}" data-field="ratio" aria-label="Leg ${i+1} ratio" type="number" min="1" max="2" step="1" value="${Math.abs(l.ratio)}"></td><td id="leg-bid-${i}"></td><td id="leg-ask-${i}"></td><td id="leg-delta-${i}"></td><td><button data-remove="${i}" aria-label="Remove leg ${i+1}">×</button></td></tr>`).join('');$('add-leg').disabled=legs.length>=4;}
  function intrinsic(p,spot){return p.legs.reduce((v,l)=>v+l.ratio*Math.max(0,l.type==='call'?spot-l.strike:l.strike-spot),(p.stockRatio||0)*spot);}
  function greeks(p){const s=market.state.stocks[p.symbol],days=Math.max(0,(p.expiry-market.state.clock)/86400000),out={delta:(p.stockRatio||0)*p.qty*100,gamma:0,theta:0,vega:0};for(const l of p.legs){const g=option(s.price,l.strike,days,s.vol,l.type);for(const k in out)out[k]+=g[k]*l.ratio*p.qty*100;}return out;}
  function plot(p,risk){const c=$('strategy-payoff'),rect=c.getBoundingClientRect();if(!rect.width)return;const d=root.devicePixelRatio||1,w=rect.width,h=rect.height;c.width=w*d;c.height=h*d;const ctx=c.getContext('2d');ctx.scale(d,d);const spot=underlying().price,min=Math.max(0,Math.min(spot,...p.legs.map(l=>l.strike))*.85),max=Math.max(spot,...p.legs.map(l=>l.strike))*1.15;
   const data=Array.from({length:201},(_,i)=>{const x=min+(max-min)*i/200;return {x,y:(intrinsic(p,x)-risk.entry)*100*p.qty};}),low=Math.min(0,...data.map(a=>a.y)),high=Math.max(1,...data.map(a=>a.y)),pad=(high-low)*.12,x=v=>64+(v-min)/(max-min)*(w-84),y=v=>h-32-(v-low+pad)/(high-low+2*pad)*(h-58);
   ctx.font='9px Arial';ctx.lineWidth=1;for(let i=0;i<5;i++){const val=low+(high-low)*i/4;ctx.strokeStyle='#e8eef2';ctx.beginPath();ctx.moveTo(64,y(val));ctx.lineTo(w-20,y(val));ctx.stroke();ctx.fillStyle='#8599a7';ctx.fillText(money(val),0,y(val)+3);}ctx.setLineDash([3,3]);ctx.strokeStyle='#829caa';ctx.beginPath();ctx.moveTo(64,y(0));ctx.lineTo(w-20,y(0));ctx.moveTo(x(spot),15);ctx.lineTo(x(spot),h-32);ctx.stroke();ctx.setLineDash([]);ctx.fillText('Spot '+money(spot),Math.min(w-105,x(spot)+5),12);
   for(let i=1;i<data.length;i++){const a=data[i-1],b=data[i];ctx.beginPath();ctx.moveTo(x(a.x),y(a.y));ctx.lineTo(x(b.x),y(b.y));ctx.strokeStyle=b.y>=0?'#16836c':'#c35459';ctx.lineWidth=2;ctx.stroke();}ctx.fillStyle='#8599a7';for(let i=0;i<4;i++){const v=min+(max-min)*i/3;ctx.fillText('$'+v.toFixed(0),x(v)-13,h-10);}
  }
  function portfolio(){const packages=market.state.packages;let g={delta:0,gamma:0,theta:0,vega:0};for(const p of market.state.positions){if(p.asset==='stock'){g.delta+=p.qty;continue;}const a=greeks({...p,legs:[{type:p.type,strike:p.strike,ratio:1}]});for(const k in g)g[k]+=a[k];}for(const p of packages){const a=greeks(p);for(const k in g)g[k]+=a[k];}
   $('portfolio-risk').innerHTML=[['Reserved collateral',money(market.collateral())],['Cash balance',money(market.state.cash)],['Delta · shares',g.delta.toFixed(2)],['Gamma · shares / $',g.gamma.toFixed(3)],['Theta · $ / day',money(g.theta)],['Vega · $ / vol point',money(g.vega)]].map(([k,v])=>`<div><label>${k}</label><b>${v}</b></div>`).join('');
   $('strategy-positions').innerHTML=packages.length?packages.map(p=>{const value=market.packageQuote(p,'mid'),gain=(value-p.entry)*p.qty*100;return `<div class="strategy-position"><div><b>${esc(p.name)} · ${p.symbol}</b><small>${p.qty} unit(s) · expires ${new Date(p.expiry).toLocaleDateString()} · ${((p.stockRatio?['+100 shares']:[]).concat(p.legs.map(l=>(l.ratio>0?'+':'')+l.ratio+' '+l.strike+' '+l.type))).join(' / ')}</small></div><div><label>Market value</label><b>${money(value*p.qty*100)}</b></div><div><label>Unrealized P/L</label><b class="${gain>=0?'positive':'negative'}">${money(gain)}</b></div><div><label>Collateral</label><b>${money(p.collateral*p.qty)}</b></div><button class="outline" data-close-package="${p.id}">Close strategy</button></div>`;}).join(''):'<div class="empty">Build a spread, straddle, strangle, iron condor, or butterfly in Strategy lab.</div>';
  }
  function render(){portfolio();if($('page-research').hidden)return;if(Number($('builder-expiry').value)<=market.state.clock)expiration();const p=draft(),s=underlying(),days=Math.max(0,(p.expiry-market.state.clock)/86400000);let risk;
   try{risk=market.packageRisk(p);if(!Number.isInteger(p.qty)||p.qty<1||p.qty>50)throw Error('Enter 1–50 strategy units.');$('builder-error').textContent='Market quotes · no fees · 100 shares per contract';$('review-strategy').disabled=false;}catch(e){$('builder-error').textContent=e.message;$('review-strategy').disabled=true;$('builder-risk').innerHTML='';$('whatif-result').textContent='Correct the strategy inputs to calculate risk.';const c=$('strategy-payoff');c.getContext('2d').clearRect(0,0,c.width,c.height);return;}
   p.legs.forEach((l,i)=>{const q=market.quote({...l,symbol:p.symbol,asset:'option',expiry:p.expiry}),g=option(s.price,l.strike,days,s.vol,l.type);$('leg-bid-'+i).textContent=money(q.bid);$('leg-ask-'+i).textContent=money(q.ask);$('leg-delta-'+i).textContent=g.delta.toFixed(3);});const g=greeks(p);
   $('builder-risk').innerHTML=[[risk.entry>=0?'Net debit':'Net credit',money(Math.abs(risk.entry)*p.qty*100)],['Max profit',risk.maxProfit===Infinity?'Unlimited':money(risk.maxProfit*p.qty)],['Max loss',money(risk.maxLoss*p.qty)],['Breakeven(s)',risk.breakevens.map(money).join(' / ')||'None'],['Collateral held',money(risk.collateral*p.qty)],['Net delta',g.delta.toFixed(2)],['Theta / day',money(g.theta)],['Vega / vol point',money(g.vega)]].map(([k,v])=>`<div><label>${k}</label><b>${v}</b></div>`).join('');
   $('whatif-days').max=days;$('whatif-days').step=Math.max(.01,days/100);const elapsed=Math.min(days,Number($('whatif-days').value)),price=Number($('whatif-price').value),iv=Number($('whatif-iv').value)/100;
   if(price>0&&Number.isFinite(price)&&iv>0&&Number.isFinite(iv)){const value=p.legs.reduce((v,l)=>v+l.ratio*option(price,l.strike,Math.max(0,days-elapsed),iv,l.type).price,(p.stockRatio||0)*price),profit=(value-risk.entry)*p.qty*100;$('whatif-result').innerHTML=`<label>Model P/L after ${elapsed.toFixed(1)} days</label><strong class="${profit>=0?'positive':'negative'}">${money(profit)}</strong><p>${(days-elapsed).toFixed(1)} days remaining · theoretical midpoint valuation, before closing spread costs.</p>`;}else $('whatif-result').textContent='Enter positive price and volatility values.';
   plot(p,risk);
  }
  $('builder-template').onchange=seed;$('builder-symbol').onchange=seed;$('builder-expiry').onchange=()=>{$('whatif-days').value=0;render();};['builder-qty','whatif-price','whatif-days','whatif-iv'].forEach(id=>$(id).oninput=render);
  $('builder-legs').onchange=e=>{const i=Number(e.target.dataset.leg),field=e.target.dataset.field;if(!field)return;const l=legs[i],value=e.target.value;if(field==='side')l.ratio=Math.abs(l.ratio)*Number(value);if(field==='type')l.type=value;if(field==='strike')l.strike=Number(value);if(field==='ratio')l.ratio=Math.sign(l.ratio)*Number(value);custom=true;render();};
  $('builder-legs').onclick=e=>{const b=e.target.closest('[data-remove]');if(!b)return;if(legs.length<=1){callbacks.toast('Keep at least one option leg in this strategy.');return;}legs.splice(Number(b.dataset.remove),1);custom=true;renderLegs();render();};
  $('add-leg').onclick=()=>{if(legs.length>=4)return;legs.push({type:'call',strike:Math.round(underlying().price),ratio:1});custom=true;renderLegs();render();};
  $('review-strategy').onclick=()=>{try{const p=draft(),r=market.validatePackage(p);callbacks.review(p,[['Strategy',p.name+' · '+p.symbol],['Units',p.qty],...(p.stockRatio?[['Stock leg',100*p.qty+' shares purchased']]:[]),...p.legs.map((l,i)=>['Leg '+(i+1),(l.ratio>0?'BUY ':'SELL ')+Math.abs(l.ratio)+' × '+l.strike+' '+l.type.toUpperCase()]),['Expiration',new Date(p.expiry).toLocaleDateString()],['Estimated '+(r.entry>=0?'debit':'credit'),money(Math.abs(r.entry)*100*p.qty)],['Collateral reserved',money(r.collateral*p.qty)],['Maximum loss at quoted fill',money(r.maxLoss*p.qty)],['Execution','All legs together at current bid / ask']]);}catch(e){callbacks.toast(e.message);}};
  $('strategy-positions').onclick=e=>{const b=e.target.closest('[data-close-package]');if(!b)return;const p=market.state.packages.find(x=>x.id===b.dataset.closePackage);if(!p)return;const value=market.packageQuote(p,'close')*p.qty*100;callbacks.review({kind:'close-package',id:p.id},[['Close strategy',p.name+' · '+p.symbol],['Units',p.qty],['Estimated '+(value>=0?'credit':'debit'),money(Math.abs(value))],['Collateral released',money(p.collateral*p.qty)],['Estimated realized P/L',money(value-p.entry*p.qty*100)]]);};
  $('close-protect').onclick=()=>$('protect-dialog').close();
  $('review-protection').onclick=()=>{if(!protectedPosition)return;const qty=Number($('protect-qty').value),stop=Number($('protect-stop').value),target=Number($('protect-target').value);try{market.validate({...protectedPosition,side:'sell',qty,orderType:'stop',limit:stop,tif:'gtc'});const q=market.quote(protectedPosition);if(!Number.isFinite(target)||stop>=q.bid||target<=q.ask)throw Error('Set the stop below the bid and target above the ask.');$('protect-dialog').close();callbacks.review({kind:'bracket',position:{...protectedPosition},qty,stop,target},[['Security',market.label(protectedPosition)],['Quantity',qty],['Stop-loss trigger',money(stop)],['Take-profit limit',money(target)],['Pair behavior','First fill cancels the other exit']]);}catch(e){callbacks.toast(e.message);}};
  expiration();seed();root.addEventListener('resize',render);
  return {render,protect(p){protectedPosition=p;const q=market.quote(p);$('protect-label').textContent=market.label(p)+' · bid '+money(q.bid)+' / ask '+money(q.ask);$('protect-qty').value=Math.max(1,p.qty-market.reservedSell(p));$('protect-stop').value=Math.max(.01,q.bid*.9).toFixed(2);$('protect-target').value=(q.ask*1.15).toFixed(2);$('protect-dialog').showModal();},selectSymbol(s){$('builder-symbol').value=s;seed();},reset(){expiration();seed();}};
 }
 root.NorthstarAdvanced={create};
})(window);
