(()=>{
 'use strict';
 const $=id=>document.getElementById(id),all=s=>document.querySelectorAll(s),{Market,option,SEEDS}=Northstar;
 let storage;try{storage=window.localStorage;}catch{}const market=new Market(storage);
 let symbol=market.state.stocks[market.state.selected]?market.state.selected:'AAPL',side='buy',asset='option',contract=null,paused=false,range=180,mode='candle',page='trade',reviewOrder=null,toastTimer,optionType='call',chainFilter='put',chartPointer,pickerKey='',simulation=null,academy=null;
 const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n),num=n=>n.toLocaleString('en-US',{maximumFractionDigits:2}),sign=n=>n>=0?'+':'−',color=n=>n>=0?'positive':'negative',signed=n=>sign(n)+money(Math.abs(n));
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const date=t=>new Date(t).toLocaleDateString('en-US',{month:'short',day:'numeric'});
 function toast(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',4500);}
 function save(){const ok=market.save();$('save-status').textContent=ok?'Saved locally ✓':'Storage unavailable · changes are temporary';}
 function populate(){const options=SEEDS.map(([s,n])=>`<option value="${s}">${s} — ${n}</option>`).join('');$('trade-symbol').innerHTML=options;$('lab-symbol').innerHTML=options;$('trade-symbol').value=symbol;$('lab-symbol').value=symbol;$('speed').value=market.state.speed;setExpiries();setLabStrike();syncPicker(true);}
 function setExpiries(){const prev=$('expiry').value;const start=new Date(market.state.clock);start.setUTCHours(20,0,0,0);const friday=(5-start.getUTCDay()+7)%7;start.setUTCDate(start.getUTCDate()+(friday||7));const list=[0,7,14,28,56,84,168,350].map(d=>start.getTime()+d*86400000);if(prev&&Number(prev)>market.state.clock&&!list.includes(Number(prev)))list.unshift(Number(prev));$('expiry').innerHTML=list.map(t=>`<option value="${t}">${date(t)} · ${Math.ceil((t-market.state.clock)/86400000)}d</option>`).join('');if(list.includes(Number(prev)))$('expiry').value=prev;}
 function current(){return market.state.stocks[symbol];}
 function stepFor(p){return p<50?1:p<200?2.5:p<500?5:10;}
 function renderWatch(){const filter=$('search').value.toLowerCase();$('watchlist').innerHTML=Object.values(market.state.stocks).filter(s=>(s.symbol+' '+s.name).toLowerCase().includes(filter)).map(s=>{const change=(s.price/s.previous-1)*100;return `<button class="watch-row ${s.symbol===symbol?'active':''}" data-symbol="${s.symbol}"><div><b>${s.symbol}</b><small>${s.name}</small></div><div><b>${money(s.price)}</b><small class="${color(change)}">${sign(change)}${Math.abs(change).toFixed(2)}%</small></div></button>`;}).join('')||'<div class="empty">No symbols found.</div>';}
 function renderAccount(){const t=market.totals();$('equity').textContent=money(t.equity);$('cash').textContent=money(market.availableCash());$('market-value').textContent=money(t.market);$('unrealized').textContent=signed(t.unrealized);$('unrealized').className=color(t.unrealized);const gain=t.equity-100000;$('account-change').textContent=`${signed(gain)} (${sign(gain)}${Math.abs(gain/1000).toFixed(2)}%) all time`;$('account-change').className=color(gain);$('ticket-cash').textContent=money(market.availableCash());$('position-count').textContent=market.state.positions.length+market.state.packages.length;}
 function renderRibbon(){const items=[['S&P PROXY','SPY',10],['NASDAQ PROXY','QQQ',40],['MSFT','MSFT',1],['NVDA','NVDA',1],['ENERGY PROXY','XOM',1]];$('market-ribbon').innerHTML=items.map(([name,k,m])=>{const s=market.state.stocks[k],diff=(s.price/s.previous-1)*100,h=s.history.slice(-25),lo=Math.min(...h.map(x=>x.p)),hi=Math.max(...h.map(x=>x.p));const points=h.map((v,i)=>`${i*2},${20-(v.p-lo)/(hi-lo||1)*17}`).join(' ');return `<div class="market-item"><b>${name}</b><span>${num(s.price*m)}</span><span class="${color(diff)}">${sign(diff)}${Math.abs(diff).toFixed(2)}%</span><svg viewBox="0 0 50 23" aria-hidden="true"><polyline points="${points}" fill="none" stroke="${diff>=0?'#16836c':'#c35459'}" stroke-width="1.3"/></svg></div>`;}).join('');}
 function renderQuote(){const s=current(),change=s.price-s.previous;$('quote-symbol').innerHTML=`${symbol} <span>${['SPY','QQQ','JPM','V','DIS','BA','WMT','XOM'].includes(symbol)?'NYSE':'NASDAQ'}</span>`;$('stock-icon').textContent=symbol[0];$('quote-name').textContent=s.name;$('sim-clock').textContent='Simulated · '+new Date(market.state.clock).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});$('quote-price').textContent=money(s.price);$('quote-change').textContent=`${signed(change)} (${sign(change)}${Math.abs(change/s.previous*100).toFixed(2)}%)`;$('quote-change').className=color(change);const q=market.quote({symbol,asset:'stock'}),h=s.history.slice(-180),prices=h.map(x=>x.p);$('quote-stats').innerHTML=[['Open',money(h[0].p)],['Session high',money(Math.max(...prices))],['Session low',money(Math.min(...prices))],['Volume',num(s.volume/1e6)+'M'],['Bid / size',money(q.bid)+' / 200'],['Ask / size',money(q.ask)+' / 300'],['Previous ref.',money(s.previous)],['Model volatility',(s.vol*100).toFixed(0)+'%']].map(([k,v])=>`<div><label>${k}</label><b>${v}</b></div>`).join('');drawChart();}
 function canvasSetup(id){const c=$(id),r=c.getBoundingClientRect();if(!r.width||!r.height)return null;const d=window.devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;const ctx=c.getContext('2d');ctx.scale(d,d);return {ctx,w:r.width,h:r.height};}
 function chartData(){const h=range>1440&&current().daily?.length>=2?current().daily:current().history;const d=h.filter(p=>p.t>=market.state.clock-range*60000);return d.length>=2?d:h.slice(-2);}
 function drawChart(){const b=NorthstarCharts.draw($('chart'),chartData(),{mode,interval:Number($('candle-interval').value),sma:$('show-sma').checked,ema:$('show-ema').checked,bands:$('show-bands').checked,rsi:$('show-rsi').checked,pointer:chartPointer});if(b)$('ohlc-strip').innerHTML=`<span>${range>1440?date(b.t):new Date(b.t).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'})}</span><span>O <b>${b.o.toFixed(2)}</b></span><span>H <b>${b.h.toFixed(2)}</b></span><span>L <b>${b.l.toFixed(2)}</b></span><span>C <b class="${color(b.c-b.o)}">${b.c.toFixed(2)}</b></span><span>Vol <b>${num(b.v)}</b></span>`;}
 function renderChain(){
 const s=current(),expiry=Number($('expiry').value),step=stepFor(s.price),center=Math.round(s.price/step)*step,count=Number($('strike-count').value);$('chain-symbol').textContent=symbol;
 const both=chainFilter==='both';$('chain-head').innerHTML=both?'<tr><th colspan="4" class="calls-head">CALLS · right to buy</th><th>Strike</th><th colspan="4" class="puts-head">PUTS · right to sell</th></tr><tr><th>Delta</th><th>IV</th><th>Sell / Bid</th><th>Buy / Ask</th><th>Price</th><th>Sell / Bid</th><th>Buy / Ask</th><th>IV</th><th>Delta</th></tr>':'<tr><th>Strike</th><th>Sell / Bid</th><th>Buy / Ask</th><th>Delta</th><th>Gamma</th><th>Theta / day</th><th>Vega</th><th>IV</th><th>Open int.</th></tr>';
 $('chain-help').textContent=both?'Calls are on the left, puts on the right. Buy opens a long position; sell closes holdings.':chainFilter==='put'?'PUT OPTIONS · Buying a put benefits from a falling underlying price. Select Buy / Ask to open.':'CALL OPTIONS · Buying a call benefits from a rising underlying price. Select Buy / Ask to open.';
 $('option-chain').innerHTML=Array.from({length:count*2+1},(_,i)=>center+(i-count)*step).filter(k=>k>0).map(k=>{const base={symbol,asset:'option',strike:k,expiry},days=market.days(base),call=option(s.price,k,days,s.vol,'call'),put=option(s.price,k,days,s.vol,'put'),cq=market.quote({...base,type:'call'}),pq=market.quote({...base,type:'put'}),oi=Math.round(3200*Math.exp(-Math.abs(k-s.price)/s.price*10)+k*3)%9000;const cell=(type,side,p)=>`<td class="${type==='call'?k<s.price?'itm':'':k>s.price?'itm':''}"><button data-contract="${type}" data-strike="${k}" data-side="${side}" aria-label="${side} ${symbol} ${k} ${type}">${p.toFixed(2)}</button></td>`;const strike=`<td class="strike">${k.toFixed(2)}</td>`;if(both)return `<tr class="${k===center?'atm':''}"><td>${call.delta.toFixed(2)}</td><td>${(s.vol*100).toFixed(1)}%</td>${cell('call','sell',cq.bid)}${cell('call','buy',cq.ask)}${strike}${cell('put','sell',pq.bid)}${cell('put','buy',pq.ask)}<td>${(s.vol*100).toFixed(1)}%</td><td>${put.delta.toFixed(2)}</td></tr>`;const g=chainFilter==='put'?put:call,q=chainFilter==='put'?pq:cq;return `<tr class="${k===center?'atm':''}">${strike}${cell(chainFilter,'sell',q.bid)}${cell(chainFilter,'buy',q.ask)}<td>${g.delta.toFixed(3)}</td><td>${g.gamma.toFixed(4)}</td><td>${g.theta.toFixed(3)}</td><td>${g.vega.toFixed(3)}</td><td>${(s.vol*100).toFixed(1)}%</td><td>${num(oi)}</td></tr>`;}).join('');
 }
 function syncPicker(reset=false){
 $('option-picker').hidden=asset!=='option';if(asset!=='option')return;
 const expiry=reset?Number($('expiry').value):(contract?.expiry||Number($('ticket-expiry').value)||Number($('expiry').value)),s=current(),step=stepFor(s.price),center=Math.round(s.price/step)*step;
 const strike=reset?center:(contract?.strike||Number($('ticket-strike').value)||center);if(reset||!contract)contract={asset:'option',symbol,type:optionType,strike,expiry};else optionType=contract.type;
 const key=[symbol,expiry,strike,optionType].join('|');all('[data-option-type]').forEach(b=>b.classList.toggle('active',b.dataset.optionType===optionType));if(!reset&&key===pickerKey)return;pickerKey=key;
 $('ticket-expiry').innerHTML=$('expiry').innerHTML;if(![...$('ticket-expiry').options].some(o=>Number(o.value)===expiry)&&expiry>market.state.clock)$('ticket-expiry').add(new Option(date(expiry),expiry));$('ticket-expiry').value=expiry;
 const strikes=[...new Set([...Array.from({length:41},(_,i)=>center+(i-20)*step).filter(k=>k>0),strike])].sort((a,b)=>a-b);$('ticket-strike').innerHTML=strikes.map(k=>`<option value="${k}">${money(k)}${k===center?' · near the money':''}</option>`).join('');$('ticket-strike').value=strike;
 }
 function pickContract(){asset='option';contract={asset:'option',symbol,type:optionType,strike:Number($('ticket-strike').value),expiry:Number($('ticket-expiry').value)};renderTicket();}
 function renderDepth(){const q=market.quote({symbol,asset:'stock'});$('depth').innerHTML=Array.from({length:7},(_,i)=>{const bid=100+Math.floor(Math.random()*18)*100,ask=100+Math.floor(Math.random()*18)*100;return `<div class="depth-row" style="--bid:${bid/1900*48}%;--ask:${ask/1900*48}%"><span>${num(bid)}</span><span>${Math.max(.01,q.bid-i*.02).toFixed(2)}</span><span>${(q.ask+i*.02).toFixed(2)}</span><span>${num(ask)}</span></div>`;}).join('');}
 function ticketAsset(){return asset==='option'?contract:{symbol,asset:'stock'};}
 function renderTicket(){syncPicker();const a=ticketAsset();$('contract-info').hidden=asset!=='option';$('contract-info').textContent=contract?market.label(contract)+' · 100 shares/contract':'Choose a bid or ask in the options chain.';$('qty-label').textContent=asset==='option'?'Contracts':'Quantity';$('cost-label').textContent=side==='buy'?'cost':'proceeds';$('submit-order').textContent=`Review ${side}${asset==='option'?' '+optionType:''} order`;all('.action-tabs button').forEach(b=>b.textContent=asset==='option'?(b.dataset.side==='buy'?'Buy to open':'Sell to close'):(b.dataset.side==='buy'?'Buy':'Sell'));if(asset==='option'&&contract){const q=market.quote(contract),g=option(current().price,contract.strike,market.days(contract),current().vol,contract.type),intrinsic=Math.max(0,contract.type==='call'?current().price-contract.strike:contract.strike-current().price);$('contract-analysis').innerHTML=[['Breakeven',money(contract.strike+(contract.type==='call'?q.ask:-q.ask))],['Max loss / contract',money(q.ask*100)],['Delta',g.delta.toFixed(3)],['Theta / day',money(g.theta*100)],['Intrinsic',money(intrinsic)],['Time value',money(Math.max(0,q.mid-intrinsic))]].map(([k,v])=>`<div><small>${k}</small><b>${v}</b></div>`).join('');}all('[data-asset]').forEach(b=>b.classList.toggle('active',b.dataset.asset===asset));all('.action-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.side===side));if(!a){['ticket-bid','ticket-ask','ticket-spread','estimated'].forEach(id=>$(id).textContent='—');return;}const q=market.quote(a);$('ticket-bid').textContent=money(q.bid);$('ticket-ask').textContent=money(q.ask);$('ticket-spread').textContent=money(q.ask-q.bid);const px=['limit','stop-limit'].includes($('order-type').value)?Number($('limit-price').value):side==='buy'?q.ask:q.bid;$('estimated').textContent=money(Math.max(0,Number($('quantity').value)||0)*px*(asset==='option'?100:1));}
 function renderPortfolio(){const ps=market.state.positions;$('positions').innerHTML=ps.length?ps.map(p=>{const q=market.quote(p),m=p.asset==='option'?100:1,gain=(q.mid-p.avg)*p.qty*m;return `<tr><td><b>${market.label(p)}</b><br><small class="muted">${p.asset==='stock'?'Equity':'Long option'}</small></td><td>${num(p.qty)}</td><td>${money(p.avg)}</td><td>${money(q.mid)}</td><td>${money(q.mid*p.qty*m)}</td><td class="${color(gain)}">${signed(gain)}</td><td><button data-protect="${esc(market.key(p))}">Protect</button> <button data-close="${esc(market.key(p))}">Sell →</button></td></tr>`;}).join(''):'<tr><td colspan="7"><div class="empty">Your portfolio starts with your first trade.<br>Head to the trading overview to buy shares or options.</div></td></tr>';$('orders').innerHTML=market.state.orders.length?market.state.orders.map(o=>`<div class="activity-row"><div><b>${o.side.toUpperCase()} ${o.qty} ${market.label(o)}</b><small>${o.orderType.toUpperCase()} ${o.orderType==='market'?'':o.orderType==='trailing'?o.trail+'% · trigger '+money(o.trigger):money(o.limit)}${o.orderType==='stop-limit'?' · stop '+money(o.trigger):''} · ${o.tif.toUpperCase()}${o.oco?' · OCO paired exit':''}${o.triggered?' · Triggered':''}</small></div><span class="muted">${date(o.created)}</span><button data-cancel="${o.id}">Cancel order</button></div>`).join(''):'<div class="empty">No open orders. Limit and stop orders will appear here.</div>';$('activity').innerHTML=market.state.activity.length?market.state.activity.slice(0,100).map(a=>`<div class="activity-row"><div><b>${esc(a.message)}</b><small>${esc(a.detail)}</small></div><span class="muted">${date(a.time)} · ${new Date(a.time).toLocaleTimeString('en-US')}</span></div>`).join(''):'<div class="empty">Your trading history will appear here.</div>';}
 function selectSymbol(s){symbol=s;market.state.selected=s;contract=null;$('trade-symbol').value=s;syncPicker(true);render();save();}
 function navigate(p){page=p;if(p==='missions'){paused=true;$('pause').textContent='▶';$('pause').title='Resume simulation';}all('.page').forEach(e=>e.hidden=e.id!=='page-'+p);all('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));if(p==='research'){drawLab();advanced.render();}if(p==='portfolio')renderPortfolio();if(p==='trade')drawChart();simulation?.render();academy?.render();}
 function setLabStrike(){const s=market.state.stocks[$('lab-symbol').value],step=stepFor(s.price);$('lab-strike').value=Math.round(s.price/step)*step;$('lab-upper').value=Number($('lab-strike').value)+step*2;$('lab-iv').value=s.vol*100;}
 function drawLab(){const s=market.state.stocks[$('lab-symbol').value],K=Number($('lab-strike').value),upper=Number($('lab-upper').value),days=Number($('lab-days').value),vol=Number($('lab-iv').value)/100,strategy=$('lab-strategy').value;if(!(K>0&&days>0&&vol>0)||strategy==='bull'&&!(upper>K)){$('strategy-description').textContent='Enter positive model inputs. A bull call spread needs an upper strike above its lower strike.';return;}const call=option(s.price,K,days,vol,'call'),put=option(s.price,K,days,vol,'put'),uc=option(s.price,upper,days,vol,'call');let cost,fn,maxProfit,maxLoss,breakeven,desc;
 if(strategy==='call'){cost=call.price;fn=p=>Math.max(0,p-K)-cost;maxProfit='Unlimited';maxLoss=money(cost*100);breakeven=money(K+cost);desc='Long call: pay a premium for the right to buy 100 shares at the strike. Profit begins above the strike plus the premium.';}
 if(strategy==='put'){cost=put.price;fn=p=>Math.max(0,K-p)-cost;maxProfit=money((K-cost)*100);maxLoss=money(cost*100);breakeven=money(K-cost);desc='Long put: pay a premium for the right to sell 100 shares at the strike. Gains increase as the underlying falls.';}
 if(strategy==='bull'){cost=call.price-uc.price;fn=p=>Math.max(0,p-K)-Math.max(0,p-upper)-cost;maxProfit=money((upper-K-cost)*100);maxLoss=money(cost*100);breakeven=money(K+cost);desc=`Bull call spread: buy the ${money(K)} call and sell the ${money(upper)} call with the same expiration. Both profit and loss are capped. Use the advanced strategy builder above to execute this spread.`;}
 if(strategy==='straddle'){cost=call.price+put.price;fn=p=>Math.abs(p-K)-cost;maxProfit='Unlimited';maxLoss=money(cost*100);breakeven=money(K-cost)+' / '+money(K+cost);desc='Long straddle: buy a call and put at the same strike. A sufficiently large move in either direction can overcome both premiums.';}
 if(strategy==='covered'){cost=s.price-call.price;fn=p=>p-s.price+call.price-Math.max(0,p-K);maxProfit=money((K-cost)*100);maxLoss=money(Math.max(0,cost)*100);breakeven=money(cost);desc='Covered call: hold 100 shares and write a call. Premium cushions a small decline, while upside is capped. Use the covered-call template in the advanced builder to trade a stock-plus-call package.';}
 $('lab-metrics').innerHTML=[['Max profit',maxProfit],['Max loss',maxLoss],['Breakeven',breakeven]].map(([k,v])=>`<div><label>${k}</label><b>${v}</b></div>`).join('');$('strategy-description').textContent=desc;const greek={};for(const key of ['delta','gamma','theta','vega'])greek[key]=strategy==='put'?put[key]:strategy==='bull'?call[key]-uc[key]:strategy==='straddle'?call[key]+put[key]:strategy==='covered'?(key==='delta'?1:0)-call[key]:call[key];$('greeks').innerHTML=Object.entries(greek).map(([k,v])=>`<div><label>${k[0].toUpperCase()+k.slice(1)} / share</label><b>${v.toFixed(3)}</b></div>`).join('');const c=canvasSetup('payoff');if(!c)return;const {ctx,w,h}=c,min=Math.max(0,Math.min(s.price,K)*.65),max=Math.max(s.price,K,strategy==='bull'?upper:K)*1.35,vals=Array.from({length:151},(_,i)=>({p:min+(max-min)*i/150,y:fn(min+(max-min)*i/150)*100})),low=Math.min(...vals.map(v=>v.y),0),high=Math.max(...vals.map(v=>v.y),1),pad=(high-low)*.12,x=p=>58+(p-min)/(max-min)*(w-78),y=p=>h-35-(p-low+pad)/(high-low+2*pad)*(h-65);ctx.font='10px Arial';ctx.fillStyle='#91a2ae';for(let i=0;i<5;i++){let val=low+(high-low)*i/4;ctx.strokeStyle='#eaf0f4';ctx.beginPath();ctx.moveTo(58,y(val));ctx.lineTo(w-20,y(val));ctx.stroke();ctx.fillText('$'+Math.round(val).toLocaleString(),0,y(val)+4);}ctx.setLineDash([4,4]);ctx.strokeStyle='#a7b7c0';ctx.beginPath();ctx.moveTo(58,y(0));ctx.lineTo(w-20,y(0));ctx.stroke();ctx.beginPath();ctx.moveTo(x(s.price),15);ctx.lineTo(x(s.price),h-35);ctx.stroke();ctx.setLineDash([]);ctx.fillText('Spot '+money(s.price),Math.min(w-110,x(s.price)+5),15);for(let i=1;i<vals.length;i++){const a=vals[i-1],b=vals[i];ctx.beginPath();ctx.moveTo(x(a.p),y(a.y));ctx.lineTo(x(b.p),y(b.y));ctx.lineWidth=2.5;ctx.strokeStyle=b.y>=0?'#16836c':'#c35459';ctx.stroke();ctx.beginPath();ctx.moveTo(x(a.p),y(0));ctx.lineTo(x(a.p),y(a.y));ctx.lineTo(x(b.p),y(b.y));ctx.lineTo(x(b.p),y(0));ctx.fillStyle=b.y>=0?'#16836c12':'#c3545912';ctx.fill();}ctx.fillStyle='#91a2ae';for(let i=0;i<5;i++){const p=min+(max-min)*i/4;ctx.fillText('$'+p.toFixed(0),x(p)-12,h-12);}}
 function render(){renderAccount();renderRibbon();if(page==='trade'){renderWatch();renderQuote();renderChain();renderDepth();}renderTicket();if(page==='portfolio')renderPortfolio();if(page==='research')drawLab();advanced.render();simulation?.render();academy?.render();}
 all('[data-page]').forEach(b=>b.onclick=()=>{navigate(b.dataset.page);render();});$('open-lab').onclick=()=>{ $('lab-symbol').value=symbol;setLabStrike();navigate('research');};$('search').oninput=renderWatch;$('watchlist').onclick=e=>{const b=e.target.closest('[data-symbol]');if(b)selectSymbol(b.dataset.symbol);};$('trade-symbol').onchange=e=>selectSymbol(e.target.value);
 all('[data-asset]').forEach(b=>b.onclick=()=>{asset=b.dataset.asset;if(asset==='option'){$('quantity').value=1;syncPicker(!contract);}renderTicket();});all('.action-tabs button').forEach(b=>b.onclick=()=>{side=b.dataset.side;renderTicket();});['quantity','limit-price','time-in-force'].forEach(id=>$(id).oninput=renderTicket);$('order-type').onchange=()=>{const type=$('order-type').value;$('limit-wrap').hidden=['market','trailing'].includes(type);$('trigger-wrap').hidden=type!=='stop-limit';$('trail-wrap').hidden=type!=='trailing';$('limit-label').textContent=type==='stop'?'Stop price':'Limit price';const a=ticketAsset();if(a){const q=market.quote(a);$('limit-price').value=q[side==='buy'?'ask':'bid'].toFixed(2);$('trigger-price').value=q.mid.toFixed(2);}renderTicket();};$('expiry').onchange=renderChain;$('strike-count').onchange=renderChain;
 $('option-chain').onclick=e=>{const b=e.target.closest('[data-contract]');if(!b)return;contract={symbol,asset:'option',type:b.dataset.contract,strike:Number(b.dataset.strike),expiry:Number($('expiry').value)};asset='option';optionType=b.dataset.contract;side=b.dataset.side;$('quantity').value=1;const q=market.quote(contract);$('limit-price').value=(side==='buy'?q.ask:q.bid).toFixed(2);renderTicket();if(innerWidth<900)document.querySelector('.ticket').scrollIntoView({behavior:'smooth',block:'center'});};
 $('trade-form').onsubmit=e=>{e.preventDefault();try{const a=ticketAsset();if(!a)throw Error('Choose an option contract from the chain first.');reviewOrder={...a,side,qty:Number($('quantity').value),orderType:$('order-type').value,limit:Number($('limit-price').value),tif:$('time-in-force').value,trigger:Number($('trigger-price').value),trail:Number($('trail-percent').value)};market.validate(reviewOrder);const q=market.quote(a);$('review-content').innerHTML=[['Security',market.label(a)],['Action',side.toUpperCase()],['Quantity',reviewOrder.qty+(asset==='option'?' contracts':' shares')],['Order type',reviewOrder.orderType.toUpperCase()+(reviewOrder.orderType==='market'?'':reviewOrder.orderType==='trailing'?' '+reviewOrder.trail+'%':' @ '+money(reviewOrder.limit))+(reviewOrder.orderType==='stop-limit'?' · stop '+money(reviewOrder.trigger):'')],['Time in force',reviewOrder.tif.toUpperCase()],['Estimated '+(side==='buy'?'cost':'proceeds'),$('estimated').textContent],['Current quote',money(q.bid)+' bid / '+money(q.ask)+' ask']].map(([k,v])=>`<div><span>${k}</span><b>${esc(v)}</b></div>`).join('');$('review-dialog').showModal();}catch(err){toast(err.message);}};
 $('close-review').onclick=()=>$('review-dialog').close();$('confirm-order').onclick=()=>{if(!reviewOrder)return;try{if(reviewOrder.kind==='bracket'){market.placeBracket(reviewOrder.position,reviewOrder.qty,reviewOrder.stop,reviewOrder.target);}else if(reviewOrder.kind==='package'){market.placePackage(reviewOrder);toast('Strategy opened. All legs filled together.');}else if(reviewOrder.kind==='close-package'){market.closePackage(reviewOrder.id);toast('Strategy closed.');}else market.place(reviewOrder);reviewOrder=null;$('review-dialog').close();toast(market.events.splice(0).join(' · ')||'Order confirmed. Check Positions & activity for details.');save();render();}catch(err){toast(err.message);}};
 $('positions').onclick=e=>{const protect=e.target.closest('[data-protect]');if(protect){const p=market.state.positions.find(x=>market.key(x)===protect.dataset.protect);advanced.protect(p);return;}const b=e.target.closest('[data-close]');if(!b)return;const p=market.state.positions.find(x=>market.key(x)===b.dataset.close);selectSymbol(p.symbol);asset=p.asset;contract=asset==='option'?{...p}:null;side='sell';$('quantity').value=p.qty;$('order-type').value='market';$('limit-wrap').hidden=true;$('trigger-wrap').hidden=true;$('trail-wrap').hidden=true;navigate('trade');render();};$('orders').onclick=e=>{const b=e.target.closest('[data-cancel]');if(b){market.cancel(b.dataset.cancel);save();renderPortfolio();toast('Order canceled.');}};
 $('timeframes').onclick=e=>{const b=e.target.closest('[data-range]');if(!b)return;range=Number(b.dataset.range);$('candle-interval').value=range>1440?'1440':'5';all('[data-range]').forEach(x=>x.classList.toggle('active',x===b));drawChart();};$('line-mode').onclick=()=>{mode='line';$('line-mode').classList.add('active');$('candle-mode').classList.remove('active');drawChart();};$('candle-mode').onclick=()=>{mode='candle';$('candle-mode').classList.add('active');$('line-mode').classList.remove('active');drawChart();};$('chart').onmousemove=e=>{chartPointer=e.clientX-$('chart').getBoundingClientRect().left;drawChart();};$('chart').onmouseleave=()=>{chartPointer=undefined;drawChart();};

 $('speed').onchange=()=>{market.state.speed=Number($('speed').value);save();toast(`Simulation advances ${market.state.speed} market minute(s) every 2 seconds.`);};$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'▶':'Ⅱ';$('pause').title=paused?'Resume simulation':'Pause simulation';toast(paused?'Market simulation paused.':'Market simulation resumed.');};
 $('reset').onclick=()=>{if(!confirm('Reset all positions, orders, history, and simulated prices? Your virtual cash will return to $100,000.'))return;market.reset();symbol='AAPL';side='buy';asset='option';contract=null;reviewOrder=null;$('review-dialog').close();$('quantity').value=1;$('order-type').value='market';$('limit-wrap').hidden=true;$('trigger-wrap').hidden=true;$('trail-wrap').hidden=true;populate();advanced.reset();render();save();toast('Fresh start. Your paper account has $100,000.');};
 $('lab-symbol').onchange=()=>{setLabStrike();drawLab();};['lab-strategy','lab-strike','lab-upper','lab-days','lab-iv'].forEach(id=>$(id).oninput=drawLab);all('[data-scenario]').forEach(b=>b.onclick=()=>{market.state.scenario=b.dataset.scenario;all('[data-scenario]').forEach(x=>x.classList.toggle('active',x===b));$('scenario-info').textContent=`${{bull:'Bullish',bear:'Bearish',normal:'Balanced',volatile:'High volatility','ai-boom':'AI investment boom','ai-bust':'AI expectations reset'}[b.dataset.scenario]} market · applies to all simulated stocks.`;save();toast('Market scenario updated.');});
 $('export').onclick=()=>{const csv=[['Simulated time','Event','Detail'],...market.state.activity.map(a=>[new Date(a.time).toISOString(),a.message,a.detail])].map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='northstar-paper-activity.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 window.addEventListener('resize',()=>{if(page==='trade')drawChart();if(page==='research')drawLab();advanced.render();simulation?.render();academy?.render();});window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save();});
 const advanced=NorthstarAdvanced.create(market,{toast,onChange:()=>{save();render();},review:(order,rows)=>{reviewOrder=order;$('review-content').innerHTML=rows.map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('');$('review-dialog').showModal();}});
 all('[data-option-type]').forEach(b=>b.onclick=()=>{optionType=b.dataset.optionType;pickContract();});$('ticket-expiry').onchange=pickContract;$('ticket-strike').onchange=pickContract;
 all('[data-chain]').forEach(b=>b.onclick=()=>{chainFilter=b.dataset.chain;all('[data-chain]').forEach(x=>x.classList.toggle('active',x===b));renderChain();});
 $('build-strategy').onclick=()=>{advanced.selectSymbol(symbol);navigate('research');};
 ['candle-interval','show-sma','show-ema','show-bands','show-rsi'].forEach(id=>$(id).onchange=drawChart);
 $('chart-expand').onclick=()=>{document.querySelector('.quote-panel').classList.toggle('expanded-chart');$('chart-expand').textContent=document.querySelector('.quote-panel').classList.contains('expanded-chart')?'× Close expanded view':'⛶ Expand';drawChart();};
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.quote-panel').classList.remove('expanded-chart');$('chart-expand').textContent='⛶ Expand';drawChart();}});
 $('chart').addEventListener('wheel',e=>{e.preventDefault();range=Math.max(15,Math.min(525600,Math.round(range*(e.deltaY>0?1.2:.8))));all('[data-range]').forEach(b=>b.classList.toggle('active',Number(b.dataset.range)===range));drawChart();},{passive:false});

 simulation=NorthstarSimulation.create(market,{toast,pause:()=>{paused=true;$('pause').textContent='▶';$('pause').title='Resume simulation';},refresh:()=>{reviewOrder=null;contract=null;pickerKey='';setExpiries();syncPicker(true);range=129600;$('candle-interval').value='1440';all('[data-range]').forEach(b=>b.classList.toggle('active',Number(b.dataset.range)===range));render();save();}});
 academy=NorthstarAcademy.create({toast});

 populate();all('[data-scenario]').forEach(b=>b.classList.toggle('active',b.dataset.scenario===market.state.scenario));$('scenario-info').textContent=`${{bull:'Bullish',bear:'Bearish',normal:'Balanced',volatile:'High volatility','ai-boom':'AI investment boom','ai-bust':'AI expectations reset'}[market.state.scenario]} market · applies to all simulated stocks.`;render();save();let ticks=0;setInterval(()=>{if(paused||simulation?.busy||document.hidden)return;market.tick();if(Number($('expiry').value)<=market.state.clock){setExpiries();syncPicker(true);}if(market.events.length)toast(market.events.splice(0).join(' · '));render();if(++ticks%3===0)save();},2000);
})();
