(function(root){
 'use strict';
 const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
 const regimes={normal:'Balanced conditions: modest long-run drift with company-specific gains and losses.',bull:'A broad expansion supports stocks, but volatility and earnings misses still cause drawdowns.',bear:'A broad contraction creates downward pressure. Short-term rallies remain possible.','ai-boom':'Higher growth assumptions for NVDA, MU, AVGO, and AMD, with spillovers to AI platforms. Earnings can exceed or miss the optimistic expectations.','ai-bust':'AI valuations reset as expectations outrun demand. Semiconductor stocks face larger shocks and possible rebounds.',volatile:'Larger moves in both directions. Options face meaningful time decay even when the underlying swings.'};
 function create(market,callbacks){
  let db=null,checkpoints=[],busy=false,summary=null,loaded=false,lastRestoredId=null;
  const ready=new Promise(resolve=>{try{const req=indexedDB.open('northstar-replay',1);req.onupgradeneeded=()=>req.result.createObjectStore('checkpoints',{keyPath:'id'});req.onsuccess=()=>{db=req.result;const tx=db.transaction('checkpoints','readonly').objectStore('checkpoints').getAll();tx.onsuccess=()=>{checkpoints=tx.result.sort((a,b)=>b.created-a.created);loaded=true;renderList();resolve();};tx.onerror=()=>{loaded=true;resolve();};};req.onerror=()=>{loaded=true;resolve();};}catch{loaded=true;resolve();}});
  function rows(){return checkpoints.filter(c=>c.session===market.state.sessionId);}
  function rewindPoint(){return rows().filter(c=>c.state.clock<market.state.clock||(c.state.clock===market.state.clock&&c.id!==lastRestoredId)).sort((a,b)=>b.state.clock-a.state.clock||b.created-a.created)[0];}
  function renderList(){const old=$('checkpoint-list').value;$('checkpoint-list').innerHTML=rows().map(c=>`<option value="${c.id}">${c.label} · ${new Date(c.state.clock).toLocaleString()}</option>`).join('');if(rows().some(c=>c.id===old))$('checkpoint-list').value=old;$('rewind-last').disabled=busy||!rewindPoint();$('restore-checkpoint').disabled=busy||!rows().length;}
  async function persist(record){if(!db)return;await new Promise((resolve,reject)=>{const tx=db.transaction('checkpoints','readwrite');tx.objectStore('checkpoints').put(record);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
  async function checkpoint(label='Saved checkpoint'){
   await ready;const record={id:Date.now()+'-'+Math.random().toString(36).slice(2),created:Date.now(),session:market.state.sessionId,label,state:market.snapshot()};checkpoints.unshift(record);
   try{await persist(record);while(checkpoints.length>16){const old=checkpoints.pop();if(db)await new Promise(resolve=>{const tx=db.transaction('checkpoints','readwrite');tx.objectStore('checkpoints').delete(old.id);tx.oncomplete=resolve;tx.onerror=resolve;});}}catch{db=null;callbacks.toast('Checkpoint saved for this session only; browser storage is unavailable.');}
   renderList();return record;
  }
  function lock(value){busy=value;callbacks.pause();if(value){$('jump-progress').showModal();$('jump-progress-bar').value=0;$('jump-progress-label').textContent='0%';}else $('jump-progress').close();renderList();}
  async function advance(days,expiry=false){if(busy)return;lock(true);let before;try{const minutes=expiry?Math.min(...[...market.state.positions.filter(p=>p.asset==='option'),...market.state.packages].map(p=>(p.expiry-market.state.clock)/60000).filter(n=>n>0)):days*1440;if(!Number.isFinite(minutes)||minutes<=0||minutes>366*1440)throw Error(expiry?'Open an option position first, then jump to its expiration.':'Choose 1–366 days.');before=market.totals();await checkpoint('Before '+(expiry?'expiration':days+' day jump'));const start=market.state.clock;await market.advance(minutes,p=>{$('jump-progress-bar').value=p;$('jump-progress-label').textContent=Math.round(p*100)+'%';});const after=market.totals();summary={days:(market.state.clock-start)/86400000,before:before.equity,after:after.equity,change:after.equity-before.equity};market.state.lastJump=summary;market.events=[];callbacks.refresh();callbacks.toast('Simulation advanced '+summary.days.toFixed(1)+' days. Account change: '+money(summary.change)+'.');}catch(e){callbacks.toast(e.message);}finally{lock(false);render();}}
  async function restore(id){if(busy)return;await ready;const c=rows().find(x=>x.id===id);if(!c)return;lock(true);try{await checkpoint('Before rewind');market.restore(c.state);lastRestoredId=c.id;summary=market.state.lastJump||null;callbacks.refresh();callbacks.toast('Checkpoint restored. Forward jumps replay the same path with the same scenario and orders.');}catch(e){callbacks.toast(e.message);}finally{lock(false);render();}}
  function plot(){const c=$('simulation-equity'),r=c.getBoundingClientRect();if(!r.width)return;const d=root.devicePixelRatio||1,w=r.width,h=r.height;c.width=w*d;c.height=h*d;const ctx=c.getContext('2d');ctx.scale(d,d);const points=[...market.state.equityHistory,{t:market.state.clock,equity:market.totals().equity}],lo=Math.min(...points.map(p=>p.equity)),hi=Math.max(...points.map(p=>p.equity)),pad=Math.max(100,(hi-lo)*.15),start=points[0].t,end=points.at(-1).t,x=t=>65+(t-start)/(end-start||1)*(w-90),y=v=>h-35-(v-lo+pad)/(hi-lo+pad*2)*(h-60);ctx.font='10px Arial';for(let i=0;i<5;i++){const v=lo-pad+(hi-lo+2*pad)*i/4;ctx.fillStyle='#869aaa';ctx.fillText(money(v),0,y(v)+3);ctx.strokeStyle='#e8eef3';ctx.beginPath();ctx.moveTo(65,y(v));ctx.lineTo(w-20,y(v));ctx.stroke();}ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(x(p.t),y(p.equity)):ctx.moveTo(x(p.t),y(p.equity)));ctx.strokeStyle='#087cb7';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#869aaa';ctx.fillText(new Date(start).toLocaleDateString(),65,h-10);ctx.fillText(new Date(end).toLocaleDateString(),w-100,h-10);}
  function render(){ $('timeline-clock').textContent=new Date(market.state.clock).toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'2-digit',minute:'2-digit'});if($('page-simulation').hidden)return;const regime=market.state.scenario;$('market-regime').value=regime;$('regime-description').textContent=regimes[regime]||regimes.normal;summary=market.state.lastJump||summary;$('jump-summary').innerHTML=(summary?[['Time advanced',summary.days.toFixed(1)+' days'],['Starting equity',money(summary.before)],['Ending equity',money(summary.after)],['Gain / loss',money(summary.change)]]:[['Available cash',money(market.availableCash())],['Account value',money(market.totals().equity)],['Open positions',market.state.positions.length+market.state.packages.length],['Upcoming events',market.state.stocks?Object.keys(market.state.stocks).length:0]]).map(([k,v])=>`<div><label>${k}</label><b>${v}</b></div>`).join('');
   $('catalyst-feed').innerHTML=market.state.news.length?market.state.news.slice(0,8).map(n=>`<div class="catalyst"><span class="${n.change>=0?'positive':'negative'}">${n.symbol}<b>${n.change>=0?'+':''}${n.change.toFixed(2)}%</b></span><div><b>${n.title}</b><small>${new Date(n.t).toLocaleDateString()} · ${n.detail}</small></div></div>`).join(''):'<div class="empty">Upcoming synthetic earnings start in 7 days. Jump forward to see catalysts unfold.</div>';plot();if(loaded)renderList();
  }
  document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>advance(Number(b.dataset.jump)));$('jump-expiry').onclick=()=>advance(0,true);$('custom-jump').onclick=()=>advance(Number($('jump-days').value));$('save-checkpoint').onclick=async()=>{if(busy)return;await checkpoint();callbacks.toast(db?'Account checkpoint saved.':'Checkpoint saved for this session.');};$('restore-checkpoint').onclick=()=>restore($('checkpoint-list').value);$('rewind-last').onclick=()=>restore(rewindPoint()?.id);$('market-regime').onchange=()=>{market.state.scenario=$('market-regime').value;market.save();render();};$('jump-progress').addEventListener('cancel',e=>e.preventDefault());root.addEventListener('resize',render);ready.then(render);
  return {render,advance,restore,checkpoint,get busy(){return busy;},ready};
 }
 root.NorthstarSimulation={create};
})(window);
