const assert=require('node:assert/strict');
const {Market}=require('../js/engine');
const {aggregate,indicators}=require('../js/charts');
const storage={value:null,getItem(){return this.value},setItem(k,v){this.value=v}};
const m=new Market(storage),expiry=m.state.clock+30*86400000;
const draft={symbol:'AAPL',expiry,qty:1,name:'Bull put spread',legs:[{type:'put',strike:225,ratio:-1},{type:'put',strike:215,ratio:1}]};
const before=m.state.cash,r=m.packageRisk(draft);assert.equal(r.collateral,1000);assert(r.entry<0);assert.equal(r.maxLoss,Math.round((1000+r.entry*100)*100)/100);
const p=m.placePackage(draft);assert(m.state.cash>before);assert.equal(m.collateral(),1000);assert(Math.abs(m.availableCash()-(100000-r.maxLoss))<.01);assert(m.totals().equity<100000);
m.save();const restored=new Market(storage);assert.equal(restored.state.packages.length,1);assert.equal(restored.collateral(),1000);
assert.throws(()=>m.placePackage({...draft,qty:51}),/1–50/);
assert.throws(()=>m.placePackage({...draft,legs:[{type:'call',strike:225,ratio:-2},{type:'call',strike:235,ratio:1}]}),/Uncovered/);
assert.throws(()=>m.placePackage({...draft,legs:[{type:'put',strike:NaN,ratio:-1},{type:'put',strike:215,ratio:1}]}),/valid/);
const cash=m.state.cash,close=m.packageQuote(p,'close');m.closePackage(p.id);assert.equal(m.state.packages.length,0);assert.equal(m.collateral(),0);assert(Math.abs(m.state.cash-(cash+close*100))<.01);
const debit={...draft,name:'Bull call',legs:[{type:'call',strike:225,ratio:1},{type:'call',strike:235,ratio:-1}]};const dr=m.packageRisk(debit);assert.equal(dr.collateral,0);assert(dr.entry>0);assert(Math.abs(dr.maxProfit+dr.maxLoss-1000)<.01);
const iron={...draft,name:'Iron condor',legs:[{type:'put',strike:210,ratio:1},{type:'put',strike:220,ratio:-1},{type:'call',strike:235,ratio:-1},{type:'call',strike:245,ratio:1}]};assert.equal(m.packageRisk(iron).collateral,1000);
const settled=m.placePackage(iron);settled.expiry=m.state.clock;const snapshot=m.state.cash;m.tick();const spot=m.state.stocks.AAPL.price;const intrinsic=iron.legs.reduce((v,l)=>v+l.ratio*Math.max(0,l.type==='call'?spot-l.strike:l.strike-spot),0);assert(Math.abs(m.state.cash-snapshot-intrinsic*100)<.02);assert.equal(m.collateral(),0);
const order={asset:'stock',symbol:'AAPL',side:'buy',qty:10,orderType:'market',tif:'gtc'};m.place(order);const stock=m.state.stocks.AAPL;
const trail=m.place({...order,side:'sell',orderType:'trailing',trail:5});assert(trail.trigger<stock.price);stock.price*=1.1;m.match(trail);const high=trail.highWater;stock.price=high*.97;m.match(trail);assert(m.state.orders.some(o=>o.id===trail.id));stock.price=high*.9;m.match(trail);assert(!m.state.orders.some(o=>o.id===trail.id));assert.equal(m.state.positions.length,0);
stock.price=200;const stoplimit=m.place({...order,qty:1,orderType:'stop-limit',trigger:210,limit:211});assert(!stoplimit.triggered);stock.price=215;m.match(stoplimit);assert(stoplimit.triggered);assert(m.state.orders.some(o=>o.id===stoplimit.id));stock.price=210;m.match(stoplimit);assert(!m.state.orders.some(o=>o.id===stoplimit.id));
const t=m.state.clock;m.state.speed=8;m.tick();assert.equal(m.state.clock,t+8*60000);assert(m.state.stocks.AAPL.history.slice(-8).every(p=>p.h>=p.o&&p.h>=p.p&&p.l<=p.o&&p.l<=p.p));
const bars=aggregate([{t:60000,o:100,h:103,l:99,p:101,v:5},{t:120000,o:101,h:105,l:100,p:104,v:7},{t:360000,o:104,h:107,l:102,p:106,v:8}],5);assert.equal(bars.length,2);assert.deepEqual({o:bars[0].o,h:bars[0].h,l:bars[0].l,c:bars[0].c,v:bars[0].v},{o:100,h:105,l:99,c:104,v:12});
const data=Array.from({length:30},(_,i)=>({c:100+i}));const ind=indicators(data);assert.equal(ind[19].sma,109.5);assert.equal(ind.at(-1).rsi,100);
const protectedQty=m.state.positions[0].qty;stock.price=200;m.placeBracket({asset:'stock',symbol:'AAPL'},protectedQty,180,220);assert.equal(m.reservedSell({asset:'stock',symbol:'AAPL'}),protectedQty);assert.throws(()=>m.place({...order,side:'sell',qty:protectedQty}),/holdings/);stock.price=230;for(const o of [...m.state.orders])m.match(o);assert.equal(m.state.positions.length,0);assert.equal(m.state.orders.length,0);assert(m.state.activity.some(a=>a.message.includes('Paired OCO')));
console.log('Passed: credit/debit spreads, iron condor collateral, strategy persistence/closing/settlement, invalid risk rejection, trailing stops, stop limits, OCO reservations and sibling cancellation, OHLC aggregation, SMA and RSI.');
