// Runs a real Chrome session using the DevTools protocol, with isolated test storage.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn}=require('node:child_process'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.join(root,new URL(req.url,'http://localhost').pathname==='/'?'index.html':new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(data);});});
const wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const profile=fs.mkdtempSync(path.join(os.tmpdir(),'northstar-test-'));
 const chrome=spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless','--no-first-run','--no-default-browser-check','--disable-background-networking','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:['ignore','ignore','pipe']});
 let ws;const pending=new Map();let id=0,session;const errors=[];
 try{
  const endpoint=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Chrome startup timed out')),15000);chrome.stderr.on('data',data=>{const m=String(data).match(/DevTools listening on (ws:\/\/[^\s]+)/);if(m){clearTimeout(timer);resolve(m[1]);}});chrome.on('error',reject);});
  ws=new WebSocket(endpoint);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});
  ws.onmessage=e=>{const d=JSON.parse(e.data);if(d.id){const task=pending.get(d.id);pending.delete(d.id);d.error?task?.reject(Error(d.error.message)):task?.resolve(d.result);}else if(d.method==='Runtime.exceptionThrown')errors.push(d.params.exceptionDetails.exception?.description||d.params.exceptionDetails.text);};
  const send=(method,params={},sid=session)=>new Promise((resolve,reject)=>{const next=++id;pending.set(next,{resolve,reject});ws.send(JSON.stringify({id:next,method,params,...(sid?{sessionId:sid}:{})}));});
  const target=await send('Target.createTarget',{url:'about:blank'});session=(await send('Target.attachToTarget',{targetId:target.targetId,flatten:true})).sessionId;await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});
  const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||'Evaluation failed');return r.result.value;};
  await send('Page.navigate',{url:'http://127.0.0.1:'+server.address().port});for(let i=0;i<100;i++){if(await evaluate('!!document.querySelector("#option-chain button")'))break;await wait(100);}
  assert.equal(await evaluate('document.querySelectorAll(".watch-row").length'),22);await evaluate('document.getElementById("pause").click()');
  assert.equal(await evaluate('document.querySelectorAll("#option-chain [data-contract=put]").length'),22);
  assert.equal(await evaluate('document.getElementById("option-picker").hidden'),false);
  await evaluate('document.querySelector("[data-option-type=put]").click()');assert.match(await evaluate('document.getElementById("submit-order").textContent'),/put/);
  await evaluate('document.getElementById("trade-form").requestSubmit()');assert.equal(await evaluate('document.getElementById("review-dialog").open'),true);await evaluate('document.getElementById("confirm-order").click()');
  assert.equal(await evaluate('JSON.parse(localStorage.getItem("northstar-paper-v1")).positions[0].type'),'put');
  await evaluate('document.querySelector("[data-page=research]").click()');
  for(const name of ['bull-call','bear-put','bull-put','bear-call','straddle','strangle','condor','butterfly','covered','protective','secured','collar']){await evaluate(`document.getElementById('builder-template').value=${JSON.stringify(name)};document.getElementById('builder-template').dispatchEvent(new Event('change'))`);assert.equal(await evaluate('document.getElementById("review-strategy").disabled'),false,name);}
  await evaluate('document.getElementById("builder-template").value="condor";document.getElementById("builder-template").dispatchEvent(new Event("change"));document.getElementById("review-strategy").click()');assert.equal(await evaluate('document.getElementById("review-dialog").open'),true);await evaluate('document.getElementById("confirm-order").click()');assert.equal(await evaluate('JSON.parse(localStorage.getItem("northstar-paper-v1")).packages.length'),1);
  await evaluate('document.querySelector("[data-page=portfolio]").click()');assert.equal(await evaluate('document.querySelectorAll(".strategy-position").length'),1);assert.match(await evaluate('document.getElementById("positions").textContent'),/PUT/);
  await evaluate('document.querySelector("[data-protect]").click();document.getElementById("review-protection").click()');assert.equal(await evaluate('document.getElementById("review-dialog").open'),true);await evaluate('document.getElementById("confirm-order").click()');assert.equal(await evaluate('JSON.parse(localStorage.getItem("northstar-paper-v1")).orders.filter(o=>o.oco).length'),2);
  await send('Page.reload');await wait(700);assert.equal(await evaluate('JSON.parse(localStorage.getItem("northstar-paper-v1")).packages.length'),1);
  await evaluate('document.querySelector("[data-page=portfolio]").click();document.querySelector("[data-close-package]").click();document.getElementById("confirm-order").click()');assert.equal(await evaluate('JSON.parse(localStorage.getItem("northstar-paper-v1")).packages.length'),0);
  await evaluate('document.querySelector("[data-page=trade]").click();document.getElementById("show-rsi").click();document.getElementById("show-bands").click();document.getElementById("chart-expand").click()');assert.equal(await evaluate('document.querySelector(".quote-panel").classList.contains("expanded-chart")'),true);await evaluate('document.getElementById("chart-expand").click()');
  const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync('/tmp/northstar-desktop.png',Buffer.from(shot.data,'base64'));
  await evaluate('document.querySelector("[data-page=research]").click()');const research=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync('/tmp/northstar-research.png',Buffer.from(research.data,'base64'));await evaluate('document.querySelector("[data-page=trade]").click()');
  await evaluate('document.querySelector("[data-page=simulation]").click();document.getElementById("market-regime").value="ai-boom";document.getElementById("market-regime").dispatchEvent(new Event("change"))');
  const beforeJump=await evaluate('localStorage.getItem("northstar-paper-v1")');
  await evaluate(`document.querySelector('[data-jump="30"]').click()`);for(let i=0;i<200;i++){if(!await evaluate('document.getElementById("jump-progress").open'))break;await wait(50);}
  const afterJump=await evaluate('JSON.parse(localStorage.getItem("northstar-paper-v1"))');assert.equal(afterJump.clock,JSON.parse(beforeJump).clock+30*86400000);assert(afterJump.news.length>0);assert(await evaluate('document.getElementById("checkpoint-list").options.length')>0);
  const simulationShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync('/tmp/northstar-simulation.png',Buffer.from(simulationShot.data,'base64'));
  await evaluate('document.getElementById("rewind-last").click()');for(let i=0;i<200;i++){if(!await evaluate('document.getElementById("jump-progress").open'))break;await wait(50);}assert.equal(await evaluate('localStorage.getItem("northstar-paper-v1")'),beforeJump);
  await evaluate('document.querySelector("[data-page=missions]").click()');assert.equal(await evaluate('document.querySelectorAll("[data-mission]").length'),16);
  const accountBeforeAcademy=await evaluate('localStorage.getItem("northstar-paper-v1")');
  await evaluate(`for(const m of NorthstarAcademy.lessons){document.querySelector('[data-mission="'+m.id+'"]').click();document.getElementById('mission-opening').value=m.legs[0].ratio>0?'Buy to open':'Sell to open';document.getElementById('mission-open').click();document.getElementById('mission-atm').click();if(!document.querySelector('.money-badge.atm'))throw Error('ATM inspection failed: '+m.id);document.querySelector('[data-lesson-days="expiry"]').click();document.querySelector('[data-question="0"][data-answer="'+m.check[2]+'"]').click();document.querySelector('[data-question="1"][data-answer="'+(m.legs[0].ratio>0?1:0)+'"]').click();document.querySelector('[data-question="2"][data-answer="0"]').click();}`);
  assert.equal(await evaluate('Object.values(JSON.parse(localStorage.getItem("northstar-academy-v1")).progress).filter(p=>p.completed).length'),16);assert.equal(await evaluate('localStorage.getItem("northstar-paper-v1")'),accountBeforeAcademy);assert.match(await evaluate('document.getElementById("academy-score").textContent'),/2,400 XP/);
  await evaluate('document.querySelector("[data-mission=long-call]").click();document.getElementById("mission-rewind").click();document.getElementById("mission-atm").click()');const academyShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync('/tmp/northstar-academy.png',Buffer.from(academyShot.data,'base64'));
  await send('Page.reload');await wait(700);await evaluate('document.querySelector("[data-page=missions]").click()');assert.match(await evaluate('document.getElementById("academy-score").textContent'),/2,400 XP/);
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await wait(100);assert(await evaluate('document.documentElement.scrollWidth <= innerWidth'), 'Mobile page overflow');
  const mobile=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync('/tmp/northstar-mobile.png',Buffer.from(mobile.data,'base64'));assert.deepEqual(errors,[]);
  console.log('Passed: real Chrome trades, 12 templates, OCO exits, 30-day advance, checkpoint rewind, all 16 missions with 2,400 XP, isolated training balances, reload persistence, charts, mobile overflow, no runtime errors. Screenshots under /tmp/northstar-*.png.');
 }finally{ws?.close();chrome.kill();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
