const assert=require('node:assert/strict');
const {Market,option,KEY}=require('../js/engine.js');
const store=()=>({data:{},getItem(k){return this.data[k]||null},setItem(k,v){this.data[k]=v}});
const memory=store(),m=new Market(memory);
const buy=(extra={})=>({asset:'stock',symbol:'AAPL',side:'buy',qty:10,orderType:'market',tif:'gtc',...extra});
assert.equal(Object.keys(m.state.stocks).length,22);
assert.equal(m.totals().equity,100000);
m.place(buy());assert.equal(m.state.positions[0].qty,10);assert(m.state.cash<100000);
const savedCash=m.state.cash;m.save();const restored=new Market(memory);assert.equal(restored.state.cash,savedCash);assert.equal(restored.state.positions[0].qty,10);
assert.throws(()=>m.place(buy({qty:1.5})),/whole quantity/);
assert.throws(()=>m.place(buy({qty:1000000})),/Insufficient cash/);
assert.throws(()=>m.place(buy({side:'sell',qty:11})),/holdings/);
const pending=m.place(buy({orderType:'limit',limit:1}));assert(m.state.orders.some(o=>o.id===pending.id));m.tick();assert(m.state.orders.some(o=>o.id===pending.id));m.cancel(pending.id);assert(!m.state.orders.some(o=>o.id===pending.id));
const ioc=m.place(buy({orderType:'limit',limit:1,tif:'ioc'}));assert(!m.state.orders.some(o=>o.id===ioc.id));
const stop=m.place(buy({orderType:'stop',limit:1000}));assert(m.state.orders.some(o=>o.id===stop.id));m.cancel(stop.id);
const limitSell=m.place(buy({side:'sell',orderType:'limit',limit:1000}));assert.throws(()=>m.place(buy({side:'sell',qty:1})),/holdings/);m.cancel(limitSell.id);m.place(buy({side:'sell'}));assert.equal(m.state.positions.length,0);
const call=option(100,100,30,.3,'call'),put=option(100,100,30,.3,'put');assert(call.price>0&&call.delta>0&&call.delta<1);assert(put.delta<0&&put.delta>-1);assert(Math.abs((call.price-put.price)-(100-100*Math.exp(-.04*30/365)))<1e-8);
const a={asset:'option',symbol:'AAPL',type:'call',strike:200,expiry:m.state.clock+86400000};const before=m.state.cash;m.place(buy({...a,qty:1}));assert.equal(m.state.positions[0].qty,1);assert(before-m.state.cash>100);m.state.positions[0].expiry=m.state.clock;m.tick();assert.equal(m.state.positions.length,0);assert(m.state.activity.some(a=>a.message.includes('settlement')));
assert.throws(()=>m.place(buy({...a,expiry:m.state.clock-1,qty:1})),/unexpired/);
for(let i=0;i<50;i++)m.tick();assert(m.state.cash>=0);assert(Object.values(m.state.stocks).every(s=>s.price>0&&s.history.length===1440));
memory.setItem(KEY,'{broken');assert.equal(new Market(memory).state.cash,100000);
const unavailable=new Market({getItem(){throw Error('blocked')},setItem(){throw Error('quota')}});assert.equal(unavailable.save(),false);
m.reset();assert.equal(m.state.cash,100000);assert.equal(m.state.positions.length,0);assert.equal(m.state.orders.length,0);
console.log('Passed: account math, persistence, order validation, limits, stops, IOC, sell reservations, options pricing, expiry settlement, simulation, reset, storage failures.');
