const assert=require('node:assert/strict');
const {Market}=require('../js/engine');
const {lessons,payoff,evaluate,delivery}=require('../js/academy');
const memory={data:null,getItem(){return this.data},setItem(k,v){this.data=v}};
(async()=>{
 const m=new Market(memory),start=m.snapshot();m.state.scenario='ai-boom';const baseline=m.snapshot();
 await m.advance(90*1440);const forward=m.snapshot();assert.equal(m.state.clock,baseline.clock+90*86400000);assert(m.state.news.length>0);assert(m.state.stocks.NVDA.daily.length>=90);assert(m.state.equityHistory.length>100);assert(m.state.stocks.NVDA.price!==baseline.stocks.NVDA.price);assert(memory.data.length<2500000,'Packed state should remain within typical localStorage quota');
 m.restore(baseline);await m.advance(90*1440);assert.deepEqual(m.snapshot(),forward,'Replaying the same checkpoint must reproduce the entire account, prices, and news');
 m.restore(baseline);m.state.scenario='ai-bust';await m.advance(90*1440);assert(m.state.stocks.NVDA.price<forward.stocks.NVDA.price,'Boom and reset scenarios should differ for the same random path');
 m.restore(baseline);m.place({symbol:'NVDA',asset:'stock',side:'buy',qty:5,orderType:'market',tif:'gtc'});await m.advance(1440);const tradedPrice=m.state.stocks.NVDA.price;m.restore(baseline);await m.advance(1440);assert.equal(m.state.stocks.NVDA.price,tradedPrice,'Order-fill randomness must not change the market path');
 m.restore(start);const expiry=m.state.clock+86400000+17123;m.place({symbol:'NVDA',asset:'option',type:'call',strike:130,expiry,side:'buy',qty:1,orderType:'market',tif:'gtc'});const withPosition=m.snapshot();await m.advance((expiry-m.state.clock)/60000);assert.equal(m.state.clock,expiry);assert.equal(m.state.positions.length,0);assert(m.state.activity.some(a=>a.message.includes('expired')));m.restore(withPosition);assert.equal(m.state.positions.length,1);assert.equal(m.state.cash,withPosition.cash);
 const credit={symbol:'MU',expiry:m.state.clock+30*86400000,qty:1,name:'Cash-secured put',stockRatio:0,legs:[{type:'put',strike:180,ratio:-1}]};assert.equal(m.packageRisk(credit).collateral,18000);m.placePackage(credit);assert.equal(m.collateral(),18000);
 const covered={symbol:'NVDA',expiry:credit.expiry,qty:1,name:'Covered call',stockRatio:1,legs:[{type:'call',strike:150,ratio:-1}]};const risk=m.packageRisk(covered);assert.equal(risk.collateral,0);assert(Number.isFinite(risk.maxProfit));const position=m.placePackage(covered);assert.equal(position.stockRatio,1);m.save();const loaded=new Market(memory);assert.equal(loaded.state.packages.at(-1).stockRatio,1);assert.deepEqual(loaded.state.stocks.NVDA.history,m.state.stocks.NVDA.history);
 // Existing version-one accounts must retain balances when new symbols are added.
 const legacy=start;delete legacy.stocks.MU;delete legacy.stocks.AVGO;legacy.cash=54321;memory.data=JSON.stringify(legacy);const migrated=new Market(memory);assert.equal(migrated.state.cash,54321);assert(migrated.state.stocks.MU&&migrated.state.stocks.AVGO);
 assert.equal(lessons.length,16);const examples={'long-call':[220,2200],'short-call':[220,-2200],'long-put':[160,2400],'short-put':[150,-3400],covered:[220,2500],protective:[180,-2400],secured:[120,-5500],'bull-call':[400,2800],'bear-put':[170,1800],'bull-put':[430,-1400],'bear-call':[300,-1500],straddle:[360,3100],'short-straddle':[150,-12100],strangle:[380,3500],collar:[320,3000],condor:[290,-600]};
 for(const lesson of lessons){const [spot,expected]=examples[lesson.id];assert.equal(payoff(lesson,spot),expected,lesson.id);assert(Math.abs(delivery(lesson,spot).equity-100000-expected)<1e-6,'Delivery parity '+lesson.id);assert(Math.abs(evaluate(lesson,0,spot).pnl)<1e-6,'Opening P/L '+lesson.id);assert(Math.abs(evaluate(lesson,lesson.days,spot).pnl-expected)<1e-6,'Expiry P/L '+lesson.id);for(const l of evaluate(lesson,lesson.days/2,spot).legs)assert(l.extrinsic>=0);}
 const call=lessons[0];assert.equal(payoff(call,195),-300);assert.equal(payoff(call,198),0);const atm=evaluate(call,45,220,false,190);assert.equal(atm.legs[0].moneyness,'ATM');assert(atm.legs[0].extrinsic>0);assert.equal(atm.legs[0].intrinsic,0);
 console.log('Passed: 90-day simulation, deterministic rewind/replay, scenario divergence, exact expiry, packed persistence, legacy migration, stock-option strategies, all 16 mission P/L examples, physical-delivery parity, and ATM time value.');
})().catch(e=>{console.error(e);process.exitCode=1});
